config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'pages/login'
  get 'pages/register'

  # get 'devise/sessions/lender-sign-in', to: "lenders#lender_sign_in", as: "lender-sign-in"
  devise_for :borrowers, controllers: { registrations: 'registrations' }
  devise_for :lenders, controllers: { registrations: 'registrations' }

  # devise_scope :borrower do 
  # 	get ''
  # end

  # get '/borrowers' => 'pages#register'

  get 'dashboard' => 'dashboard#home'

  resources :dashboard
  # resources :borrowers
  # resources :lenders

  get '*path', to: redirect('/error')

end

app/models/borrower.rb
class Borrower < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :secure_validatable, password_length: 6..24
  validates :first_name, length: { maximum: 30 }
  validates :last_name, length: { maximum: 30 }
  validates :street, length: { maximum: 25 }
  validates :zip, length: { maximum: 5 }
end

app/controllers/borrowers_controller.rb
class BorrowersController < ApplicationController
  before_action :set_borrower, only: [:show, :edit, :update, :destroy]

  # GET /borrowers
  # GET /borrowers.json
  def index
    # @borrowers = Borrower.all
  end

  # GET /borrowers/1
  # GET /borrowers/1.json
  def show
  end

  # GET /borrowers/new
  def new
    @borrower = Borrower.new
  end

  # GET /borrowers/1/edit
  def edit
  end

  # POST /borrowers
  # POST /borrowers.json
  def create
    @borrower = Borrower.new(borrower_params)

    respond_to do |format|
      if @borrower.save
        format.html { redirect_to @borrower, notice: 'Borrower was successfully created.' }
        format.json { render :show, status: :created, location: @borrower }
      else
        format.html { render :new }
        format.json { render json: @borrower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /borrowers/1
  # PATCH/PUT /borrowers/1.json
  def update
    respond_to do |format|
      if @borrower.update(borrower_params)
        format.html { redirect_to @borrower, notice: 'Borrower was successfully updated.' }
        format.json { render :show, status: :ok, location: @borrower }
      else
        format.html { render :edit }
        format.json { render json: @borrower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrowers/1
  # DELETE /borrowers/1.json
  def destroy
    @borrower.destroy
    respond_to do |format|
      format.html { redirect_to borrowers_url, notice: 'Borrower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrower
      @borrower = Borrower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def borrower_params
      params.require(:borrower).permit(:first_name, :last_name, :email, :phone, :street, :state, :zip, :company_name, :employer_street, :employer_state, :employer_zip, :current_position, :start_date, :salary)
    end
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/views/borrowers/_form.html.erb
<%= form_with(model: borrower, local: true) do |form| %>
  <% if borrower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(borrower.errors.count, "error") %> prohibited this borrower from being saved:</h2>

      <ul>
      <% borrower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :borrower_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :borrower_last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :borrower_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone, id: :borrower_phone %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street, id: :borrower_street %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :borrower_state %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.number_field :zip, id: :borrower_zip %>
  </div>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name, id: :borrower_company_name %>
  </div>

  <div class="field">
    <%= form.label :employer_street %>
    <%= form.text_field :employer_street, id: :borrower_employer_street %>
  </div>

  <div class="field">
    <%= form.label :employer_state %>
    <%= form.text_field :employer_state, id: :borrower_employer_state %>
  </div>

  <div class="field">
    <%= form.label :employer_zip %>
    <%= form.number_field :employer_zip, id: :borrower_employer_zip %>
  </div>

  <div class="field">
    <%= form.label :current_position %>
    <%= form.text_field :current_position, id: :borrower_current_position %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.text_field :start_date, id: :borrower_start_date %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.number_field :salary, id: :borrower_salary %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/borrowers/edit.html.erb
<h1>Editing Borrower</h1>

<%= render 'form', borrower: @borrower %>

<%= link_to 'Show', @borrower %> |
<%= link_to 'Back', borrowers_path %>

app/views/borrowers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Borrowers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Street</th>
      <th>State</th>
      <th>Zip</th>
      <th>Company name</th>
      <th>Employer street</th>
      <th>Employer state</th>
      <th>Employer zip</th>
      <th>Current position</th>
      <th>Start date</th>
      <th>Salary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @borrowers.each do |borrower| %>
      <tr>
        <td><%= borrower.first_name %></td>
        <td><%= borrower.last_name %></td>
        <td><%= borrower.email %></td>
        <td><%= borrower.phone %></td>
        <td><%= borrower.street %></td>
        <td><%= borrower.state %></td>
        <td><%= borrower.zip %></td>
        <td><%= borrower.company_name %></td>
        <td><%= borrower.employer_street %></td>
        <td><%= borrower.employer_state %></td>
        <td><%= borrower.employer_zip %></td>
        <td><%= borrower.current_position %></td>
        <td><%= borrower.start_date %></td>
        <td><%= borrower.salary %></td>
        <td><%= link_to 'Show', borrower %></td>
        <td><%= link_to 'Edit', edit_borrower_path(borrower) %></td>
        <td><%= link_to 'Destroy', borrower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Borrower', new_borrower_path %>

app/views/borrowers/new.html.erb
<h1>New Borrower</h1>

<%= render 'form', borrower: @borrower %>

<%= link_to 'Back', borrowers_path %>

app/views/borrowers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @borrower.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @borrower.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @borrower.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @borrower.phone %>
</p>

<p>
  <strong>Street:</strong>
  <%= @borrower.street %>
</p>

<p>
  <strong>State:</strong>
  <%= @borrower.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @borrower.zip %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @borrower.company_name %>
</p>

<p>
  <strong>Employer street:</strong>
  <%= @borrower.employer_street %>
</p>

<p>
  <strong>Employer state:</strong>
  <%= @borrower.employer_state %>
</p>

<p>
  <strong>Employer zip:</strong>
  <%= @borrower.employer_zip %>
</p>

<p>
  <strong>Current position:</strong>
  <%= @borrower.current_position %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @borrower.start_date %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @borrower.salary %>
</p>

<%= link_to 'Edit', edit_borrower_path(@borrower) %> |
<%= link_to 'Back', borrowers_path %>