config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'pages/login'
  get 'pages/register'

  # get 'devise/sessions/lender-sign-in', to: "lenders#lender_sign_in", as: "lender-sign-in"
  devise_for :borrowers, controllers: { registrations: 'registrations' }
  devise_for :lenders, controllers: { registrations: 'registrations' }

  # devise_scope :borrower do 
  # 	get ''
  # end

  # get '/borrowers' => 'pages#register'

  get 'dashboard' => 'dashboard#home'

  resources :dashboard
  # resources :borrowers
  # resources :lenders

  get '*path', to: redirect('/error')

end

app/models/lender.rb
class Lender < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :secure_validatable, password_length: 6..24
  validates :first_name, length: { maximum: 30 }
  validates :last_name, length: { maximum: 30 }
  validates :street, length: { maximum: 25 }
  validates :zip, length: { maximum: 5 }
end

app/controllers/lenders_controller.rb
class LendersController < ApplicationController
  before_action :set_lender, only: [:show, :edit, :update, :destroy]

  # GET /lenders
  # GET /lenders.json
  def index
    # @lenders = Lender.all
  end

  # GET /lenders/1
  # GET /lenders/1.json
  def show
  end

  # GET /lenders/new
  def new
    @lender = Lender.new
    
  end

  # GET /lenders/1/edit
  def edit
  end

  # POST /lenders
  # POST /lenders.json
  def create
    @lender = Lender.new(lender_params)

    respond_to do |format|
      if @lender.save
        format.html { redirect_to @lender, notice: 'Lender was successfully created.' }
        format.json { render :show, status: :created, location: @lender }
      else
        format.html { render :url => 'pages/register'}
        format.json { render json: @lender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lenders/1
  # PATCH/PUT /lenders/1.json
  def update
    respond_to do |format|
      if @lender.update(lender_params)
        format.html { redirect_to @lender, notice: 'Lender was successfully updated.' }
        format.json { render :show, status: :ok, location: @lender }
      else
        format.html { render :edit }
        format.json { render json: @lender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lenders/1
  # DELETE /lenders/1.json
  def destroy
    @lender.destroy
    respond_to do |format|
      format.html { redirect_to lenders_url, notice: 'Lender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lender
      @lender = Lender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lender_params
      params.require(:lender).permit(:first_name, :last_name, :email, :phone, :street, :state, :zip)
    end
end

app/helpers/lenders_helper.rb
module LendersHelper
end

app/views/lenders/_form.html.erb
<%= form_with(model: lender, local: true) do |form| %>
  <% if lender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lender.errors.count, "error") %> prohibited this lender from being saved:</h2>

      <ul>
      <% lender.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :lender_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :lender_last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :lender_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone, id: :lender_phone %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street, id: :lender_street %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :lender_state %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.number_field :zip, id: :lender_zip %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lenders/edit.html.erb
<h1>Editing Lender</h1>

<%= render 'form', lender: @lender %>

<%= link_to 'Show', @lender %> |
<%= link_to 'Back', lenders_path %>

app/views/lenders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lenders</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Street</th>
      <th>State</th>
      <th>Zip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lenders.each do |lender| %>
      <tr>
        <td><%= lender.first_name %></td>
        <td><%= lender.last_name %></td>
        <td><%= lender.email %></td>
        <td><%= lender.phone %></td>
        <td><%= lender.street %></td>
        <td><%= lender.state %></td>
        <td><%= lender.zip %></td>
        <td><%= link_to 'Show', lenders_path %></td>
        <td><%= link_to 'Edit', edit_lender_path(lender) %></td>
        <td><%= link_to 'Destroy', lender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lender', new_lender_path %>

app/views/lenders/new.html.erb
<h1>New Lender</h1>

<%= render 'form', lender: @lender %>

<%= link_to 'Back', lenders_path %>

app/views/lenders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @lender.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @lender.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @lender.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @lender.phone %>
</p>

<p>
  <strong>Street:</strong>
  <%= @lender.street %>
</p>

<p>
  <strong>State:</strong>
  <%= @lender.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @lender.zip %>
</p>

<%= link_to 'Edit', edit_lender_path(@lender) %> |
<%= link_to 'Back', lenders_path %>