config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'pages/login'
  get 'pages/register'

  # get 'devise/sessions/lender-sign-in', to: "lenders#lender_sign_in", as: "lender-sign-in"
  devise_for :borrowers, controllers: { registrations: 'registrations' }
  devise_for :lenders, controllers: { registrations: 'registrations' }

  # devise_scope :borrower do 
  # 	get ''
  # end

  # get '/borrowers' => 'pages#register'

  get 'dashboard' => 'dashboard#home'

  resources :dashboard
  # resources :borrowers
  # resources :lenders

  get '*path', to: redirect('/error')

end

app/views/layouts/_desktop-nav.html.erb
<nav id="nav-desktop" class="nav">
  <div class="container">
    <div class="pull-left">
      <h1 class="site-title">
        Mini
        Money
        Market
      </h1>
    </div>
    <div class="pull-right">
      <ul class="nav-list">
        <%= link_to root_path do %>
          <li>Home</li>
        <% end %>

        <% if current_lender || current_borrower %>
          <%= link_to destroy_lender_session_path, method: :delete do %>
            <li>Logout</li>
          <% end %>
        <% else %>
          <%= link_to pages_login_path do %>
            <li>Login</li>
          <% end %>
        <% end %>
  
        <li>
          About
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_mobile-nav.html.erb
<div class="nav-mobile">
  <div class="mini-money-market">
    <span class="mmm">        
    mini
    money
    market
    </span>
    <div id="myNav" class="overlay">
      <!-- this will close the overlay -->
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <!-- overlay menu content -->
      <div class="overlay-content" style="margin-left: -10%;">
        <%= link_to 'Home', root_path %>
        <% if current_lender || current_borrower %>
          <%= link_to 'Dashboard', dashboard_path %>
          <%= link_to "Sign out", destroy_lender_session_path, method: :delete %>
        <% else %>
          <%= link_to "Login", pages_login_path %>
        <% end %>
          <%= link_to 'About'%>
      </div>
    </div>
    <span class="menu" onclick="openNav()" aria-hidden="true">  
      <i class="fas fa-bars"></i>
    </span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniMoneyMarket</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  </head>
  
  <%= render 'layouts/mobile-nav' %>
  <%= render 'layouts/desktop-nav' %>
  <body>
    <div class="container py-5"> 
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>